spring:
  application:
    name: financeflow

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

server:
  port: ${PORT:8080}