import { useQuery } from "@tanstack/react-query";
import { ArrowDownRight, ArrowUpRight, CreditCard, Plus, WalletCards } from "lucide-react";
import { Link } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { financeApi } from "../api/finance";
import { ErrorState, LoadingState } from "../components/ui/States";
import { PageHeader } from "../components/ui/PageHeader";
import { formatCurrency, formatDate } from "../utils/format";

function MetricCard({ label, value, trend, icon: Icon }: { label: string; value: number; trend?: "income" | "expense"; icon: typeof WalletCards }) {
  return <article className="card card-pad metric"><div className="metric-head"><span className="metric-label">{label}</span><span className="metric-icon"><Icon size={18}/></span></div><strong className="metric-value">{formatCurrency(value)}</strong>{trend && <span className={trend === "income" ? "metric-trend income" : "metric-trend expense"}>{trend === "income" ? <ArrowUpRight size={15}/> : <ArrowDownRight size={15}/>} {trend === "income" ? "Incoming" : "Outgoing"}</span>}</article>;
}

export function DashboardPage() {
  const dashboard = useQuery({ queryKey: ["dashboard"], queryFn: financeApi.dashboard });
  if (dashboard.isLoading || !dashboard.data) return <><PageHeader title="Dashboard" description="Your financial position at a glance."/><div className="metric-grid">{Array.from({ length: 4 }, (_, index) => <div className="skeleton metric" key={index}/>)}</div></>;
  if (dashboard.isError) return <><PageHeader title="Dashboard" description="Your financial position at a glance."/><ErrorState retry={() => dashboard.refetch()}/></>;
  const data = dashboard.data;
  const categories = [...data.expenseByCategory, ...data.incomeByCategory];
  const totals = [{ name: "Income", value: data.totalIncome }, { name: "Expense", value: data.totalExpense }];
  return <><PageHeader title="Dashboard" description="Your financial position at a glance." actions={<Link className="button button-primary" to="/transactions/new"><Plus size={17}/>Add transaction</Link>}/><section className="metric-grid"><MetricCard label="Current balance" value={data.totalBalance} icon={WalletCards}/><MetricCard label="Income" value={data.totalIncome} trend="income" icon={ArrowUpRight}/><MetricCard label="Expenses" value={data.totalExpense} trend="expense" icon={ArrowDownRight}/><MetricCard label="Net balance" value={data.totalIncome - data.totalExpense} icon={CreditCard}/></section><section className="dashboard-grid section-offset"><article className="card card-pad"><h2>Expense by category</h2><p className="subtle">Where your money is going.</p><div className="chart-area"><ResponsiveContainer><BarChart data={categories}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="categoryName" tick={{ fill: "var(--muted)", fontSize: 12 }}/><YAxis tick={{ fill: "var(--muted)", fontSize: 12 }}/><Tooltip/><Legend/><Bar dataKey="totalAmount" name="Amount" fill="var(--primary)" radius={[4, 4, 0, 0]}/></BarChart></ResponsiveContainer></div></article><article className="card card-pad"><h2>Income vs expense</h2><p className="subtle">Current financial mix.</p><div className="chart-area"><ResponsiveContainer><PieChart><Pie data={totals} dataKey="value" nameKey="name" outerRadius={90} fill="var(--accent)"/><Tooltip/><Legend/></PieChart></ResponsiveContainer></div></article></section><section className="card section-offset"><div className="card-pad section-heading"><div><h2>Recent transactions</h2><p className="subtle">Your latest activity.</p></div><Link className="text-link" to="/transactions">View all</Link></div>{data.recentTransactions.length ? <div className="table-wrap"><table><thead><tr><th>Description</th><th>Category</th><th>Amount</th><th>Date</th></tr></thead><tbody>{data.recentTransactions.map((transaction) => <tr key={transaction.id}><td>{transaction.description || "Untitled transaction"}</td><td><span className="badge">{transaction.categoryName}</span></td><td>{formatCurrency(transaction.amount)}</td><td>{formatDate(transaction.transactionDate)}</td></tr>)}</tbody></table></div> : <LoadingState label="No recent transactions yet"/>}</section><section className="quick-actions section-offset"><Link className="quick-action card" to="/accounts/new"><WalletCards size={20}/><span><strong>Add an account</strong><small>Track a new balance</small></span></Link><Link className="quick-action card" to="/categories/new"><Plus size={20}/><span><strong>Create a category</strong><small>Keep spending organised</small></span></Link><Link className="quick-action card" to="/rules/new"><ArrowUpRight size={20}/><span><strong>Set a rule</strong><small>Automate categorisation</small></span></Link></section></>;
}
