import type { LucideIcon } from "lucide-react";
import {
  Banknote,
  Bike,
  BookOpen,
  Briefcase,
  Bus,
  Car,
  Coffee,
  Coins,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  Music,
  PiggyBank,
  Pill,
  Plane,
  School,
  Scissors,
  Shirt,
  ShoppingCart,
  Smartphone,
  TrendingUp,
  Utensils,
  Wallet,
  Wifi,
  Zap,
} from "lucide-react";

/** Icon names available in the category icon picker (kebab-case, stored on the category). */
export const CATEGORY_ICONS = [
  "shopping-cart",
  "utensils",
  "coffee",
  "gift",
  "film",
  "music",
  "gamepad-2",
  "shirt",
  "bus",
  "car",
  "bike",
  "plane",
  "home",
  "zap",
  "wifi",
  "smartphone",
  "briefcase",
  "coins",
  "banknote",
  "piggy-bank",
  "trending-up",
  "wallet",
  "credit-card",
  "school",
  "dumbbell",
  "heart-pulse",
  "pill",
  "book-open",
  "laptop",
  "landmark",
  "scissors",
  "fuel",
] as const;

export const ICON_MAP: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  coffee: Coffee,
  gift: Gift,
  film: Film,
  music: Music,
  "gamepad-2": Gamepad2,
  shirt: Shirt,
  bus: Bus,
  car: Car,
  bike: Bike,
  plane: Plane,
  home: House,
  zap: Zap,
  wifi: Wifi,
  smartphone: Smartphone,
  briefcase: Briefcase,
  coins: Coins,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  wallet: Wallet,
  "credit-card": CreditCard,
  school: School,
  dumbbell: Dumbbell,
  "heart-pulse": HeartPulse,
  pill: Pill,
  "book-open": BookOpen,
  laptop: Laptop,
  landmark: Landmark,
  scissors: Scissors,
  fuel: Fuel,
};

export const CATEGORY_COLORS = [
  "#EF4444",
  "#F97316",
  "#F59E0B",
  "#84CC16",
  "#22C55E",
  "#10B981",
  "#06B6D4",
  "#0EA5E9",
  "#3B82F6",
  "#6366F1",
  "#8B5CF6",
  "#D946EF",
  "#EC4899",
  "#F43F5E",
  "#64748B",
  "#0F172A",
];
